#!/usr/bin/env bash

$PWD = pwd 1>/dev/null 2>&1

# Name der Datei, aus der die Zeilen gelesen werden sollen
DATEI="config/accounts/account_rest.txt"
COUNT=$(wc -l < "$DATEI")

if [[ -e "$DATEI" ]]; then
	echo "File exits: $DATEI"
else
	echo "File doesnt exits: $DATEI"
fi

if [[ -e "config/log" ]]; then
	echo "log folder exists"
else
	mkdir -p config/log
fi

# Befehl, an den die Zeilen angehängt werden
BEFEHL="yt-dlp -vU -i --yes-playlist --download-archive config/yt-archive.txt --dateafter 20241101 -o %(upload_date)s/%(uploader)s/%(title)s_%(id)s.%(ext)s --merge-output-format mp4 "
#BEFEHL2="yt-dlp -vU -i --yes-playlist --sponsorblock-remove all --download-archive config/yt-archive_sponsor.txt --dateafter 20241101 -o %(upload_date)s/%(uploader)s/%(title)s_sponsorblock_%(id)s.%(ext)s --merge-output-format mp4 "
#BEFEHL2="yt-dlp -vU -i --yes-playlist --download-archive config/yt-archive.txt --datebefore 20111231 -o %(upload_date)s/%(uploader)s/%(title)s_%(id)s.%(ext)s --merge-output-format mp4 "

#BEFEHL="yt-dlp -vF -i --yes-playlist --download-archive config/yt-archive.txt --dateafter 20231231 -o %(upload_date)s/%(uploader)s/%(title)s_%(id)s.%(ext)s --merge-output-format mp4 "
#watch -n 2 "pgrep -af yt-dlp | grep -oP 'https?://\S+'" &
#tail -f config/log/log_*  | grep -i "Extracting URL\|Downloading item\|upload date\|Video unavailable\|Finished downloading playlist\|Sign in to confirm you’re not a bot\|Downloading webpage\|Downloading playlist" &

while IFS= read -r ZEILE; do
  # Füge die Zeile an den Befehl an und führe den Befehl aus
  echo "Working on $ZEILE ($COUNT)"
  $BEFEHL $ZEILE >> config/log/log_$(date '+%Y-%m-%d').txt 2>&1
  #$BEFEHL2 $ZEILE >> config/log/log_$(date '+%Y-%m-%d').txt 2>&1
  #echo "$BEFEHL $ZEILE"
  COUNT=$((COUNT - 1))
done < "$DATEI"

# Name der Datei, aus der die Zeilen gelesen werden sollen
DATEI="config/accounts/account_music.txt"
COUNT=$(wc -l < "$DATEI")

if [[ -e "$DATEI" ]]; then
	echo "File exits: $DATEI"
else
	echo "File doesnt exits: $DATEI"
fi


# Befehl, an den die Zeilen angehängt werden
BEFEHL="yt-dlp -i -x -k --audio-format mp3 --yes-playlist --download-archive config/yt-archive.txt -o %(upload_date)s/%(uploader)s_music/%(title)s_%(id)s.%(ext)s --merge-output-format mp4"

while IFS= read -r ZEILE; do
  echo "Working on $ZEILE ($COUNT)"
  # Füge die Zeile an den Befehl an und führe den Befehl aus
  $BEFEHL $ZEILE >> config/log/log_$(date '+%Y-%m-%d').txt 2>&1
  #echo "$BEFEHL $ZEILE"
  COUNT=$((COUNT - 1))
done < "$DATEI"

