#!/bin/env bash

#extra 3
yt-dlp -i --no-warnings --get-id --download-archive config/yt-archive.txt --match-title "Realer Irrsinn" https://www.youtube.com/playlist?list=UUjhkuC_Pi85wGjnB0I1ydxw | xargs -I '{}' -P 9 brave 'https://youtube.com/watch?v={}'

yt-dlp -i --no-warnings --get-id --batch-file config/all --download-archive config/yt-archive.txt | xargs -I '{}' -P 9 brave 'https://youtube.com/watch?v={}'
yt-dlp -i --no-warnings --get-id --batch-file config/privat --download-archive config/yt-archive.txt | xargs -I '{}' -P 9 brave 'https://youtube.com/watch?v={}'

yt-dlp -i --no-warnings --get-id --batch-file config/music --download-archive config/yt-archive.txt | xargs -I '{}' -P 9 brave 'https://youtube.com/watch?v={}'


