#!/bin/env bash

accounts=("extra 3" "Tooncraft" "methodisch inkorrekt" "Joe Penna _ MysteryGuitarMan" "Fritz Meinecke" "CreepfanLP" "TechHut" "Chris Titus Tech" "SPACE FROGS" "SemperVideo" "RumbleBeast666" "Mr. Hacker" "Make Tech Easier" "marcus-s _ VR, Linux" "Marti Fischer" "STRG_F" "Dinge Erklärt – Kurzgesagt" "Matt Jordan" "euremuetterchannel" "Kurzgesagt – In a Nutshell" "Kanzlei WBS" "Lethamyr" "2 Bored Guys" "Simplicissimus" "Gebrüder Lange" "Joseph DeChangeman" "3Blue1Brown" "Veritasium" "DorFuchs" "minutephysics" "Eure Videos Fahrnünftig" "SunlessKhan" "Davis Schulz" "MythosOfGaming" "Tiemo Wölken" "Lange Reisen" "media.ccc.de" "Florian Dalwigk" "ruthe.de" "AltF4Games" "coldmirror" "rbb" "i12bretro" "JuliensBlog" "RELOADIAK" "Joseph" "Code Bullet" "Real Civil Engineer" "LockPickingLawyer" "Paweł Zadrożniak" "DIY Perks" "Gifs Sound")

rm -f playlist*

for i in "${accounts[@]}"; do

    find -type f -ipath "*20*" | grep -i "/2" | sort | uniq | grep -i "mp4\|mkv\|webm" | grep -i "$i" | head -1 >> playlist.temp
    find -type f -ipath "*20*" | grep -i "/2" | sort | uniq | grep -i "mp4\|mkv\|webm" | grep -i "$i" >> playlist_"$i".txt
    find -type f -ipath "*20*" | grep -i "/2" | sort -r | uniq | grep -i "mp4\|mkv\|webm" | grep -i "$i" | head -1 >> playlist_new.temp

done

cat playlist.temp | sort | uniq >> playlist.txt
cat playlist_new.temp | sort -r | uniq >> playlist_new.txt

rm -f playlist.temp
rm -f playlist_new.temp

find -type f | sort | grep -i "/2" | sort -r | uniq > playlist_full_nto.txt
cat playlist_full_nto.txt | sort > playlist_full_otn.txt

rm -f playlist_orderby_date_and_account.txt
find 20* -type f | awk 'BEGIN{FS="/"} {print $2"/"$1"/"$3}' | sort | awk 'BEGIN{FS="/"} {print $2"/"$1"/"$3}' >> playlist_orderby_date_and_account.txt

find -empty -delete
