#!/bin/env bash

#extra 3
yt-dlp -i --no-warnings --get-id --download-archive config/yt-archive.txt --match-title "Realer Irrsinn" https://www.youtube.com/playlist?list=UUjhkuC_Pi85wGjnB0I1ydxw | xargs -I '{}' -P 50 yt-dlp -i --download-archive config/yt-archive.txt -o './%(upload_date)s/%(uploader)s/%(title)s_%(id)s.%(ext)s' --merge-output-format mp4 'https://youtube.com/watch?v={}'

yt-dlp -i --no-warnings --get-id --batch-file config/all --download-archive config/yt-archive.txt | xargs -I '{}' -P 50 yt-dlp -i --download-archive config/yt-archive.txt -o './%(upload_date)s/%(uploader)s/%(title)s_%(id)s.%(ext)s' --merge-output-format mp4 'https://youtube.com/watch?v={}'

yt-dlp -i --no-warnings --get-id --batch-file config/privat --download-archive config/yt-archive.txt | xargs -I '{}' -P 50 yt-dlp -i --download-archive config/yt-archive.txt -o './privat/%(uploader)s/%(title)s_%(id)s.%(ext)s' --merge-output-format mp4 'https://youtube.com/watch?v={}'

yt-dlp -i --no-warnings --get-id --batch-file config/music --download-archive config/yt-archive.txt | xargs -I '{}' -P 50 yt-dlp -i -x -k --audio-format mp3 --download-archive config/yt-archive.txt -o './music/%(uploader)s/%(title)s_%(id)s.%(ext)s' --merge-output-format mp4 'https://youtube.com/watch?v={}'

